### PR TITLE
Dashboard user summary bar and progress charts labels

### PR DESCRIPTION
**Pull request by James-Lycett**
Was bored and felt like doing some easy coding so I implemented my dashboard design idea mentioned in #81 

Check it out at your leisure. Merge it if you like it, if not then hit me up.

### CODE REVIEW

**Comment by cozyfestiv** [comment]
Screenshot 2024-08-09 at 3 11 20 PM

Definitely needs some mobile formatting, lol 

Screenshot 2024-08-09 at 3 12 50 PM

also I'm gonna try and fix the color of the bar that the search is in

**Comment by cozyfestiv** [comment]
Screenshot 2024-08-09 at 3 51 05 PM

Better I think!!

**Comment by cozyfestiv** [comment]
Also Hi! I had messaged some random things on the slack, but I'm happy to move them over here if this is where you'd prefer to communicate!

**Comment by James-Lycett** [comment]
As for your changes on this pull request, looks great! 

As much as thinkful tried to train me "mobile first" and I agree with the philosophy, mobile formatting still gets relegated to an afterthought in my process really often!

Search bar color was a good idea I couldn't really figure out why that looked off but yeah it's better this way.

**Pull request merged**
